//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThienNga2.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp
    {
        public int id { get; set; }
        public string date { get; set; }
        public string name { get; set; }
        public string sdt { get; set; }
        public string fakename { get; set; }
        public string datecode { get; set; }
        public string series { get; set; }
    }
}
