//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThienNga2.Models.Entities
{
    using System;
    
    public partial class ThienNga_getkho_Result2
    {
        public int inventoryID { get; set; }
        public int quantity { get; set; }
        public string productName { get; set; }
        public string producFactoryID { get; set; }
        public string productStoreID { get; set; }
        public double price { get; set; }
        public string description { get; set; }
    }
}
